export interface Feature { slug: string; title: string; short: string; description: string; points: string[]; metric: string }
export const FEATURES: Feature[] = [
  { slug: 'cash-flow-analysis', title: 'Cash flow analysis', metric: 'Monthly surplus',
    short: 'See what is left each month after spending and EMIs.',
    description: 'FinSight converts salary, rent, groceries, EMIs and subscriptions into monthly equivalents, then shows your real monthly surplus and savings rate.',
    points: ['Weekly, quarterly and yearly items normalised to monthly', 'One-off items kept out of recurring ratios', 'Every number expands to show its formula'] },
  { slug: 'net-worth-tracker', title: 'Net worth tracker', metric: 'Assets minus liabilities',
    short: 'Assets, investments and loans in one number you can trust.',
    description: 'Add bank balances, gold, property, mutual funds, NPS, PPF and loans. FinSight keeps investments and other assets separate and totals your net worth.',
    points: ['Liquid vs illiquid assets', 'Investment allocation by category', 'Snapshots so you can compare month to month'] },
  { slug: 'debt-and-emi-review', title: 'Debt and EMI review', metric: 'Debt-service ratio',
    short: 'Learn how much of your income goes to loan payments.',
    description: 'Record home, vehicle, education and personal loans plus credit cards. FinSight calculates your debt-service ratio and warns when an EMI is missing instead of guessing.',
    points: ['Debt ratio against your own threshold', 'Missing EMI data is flagged, never assumed zero', 'Test a new loan in the scenario simulator'] },
  { slug: 'emergency-fund-planner', title: 'Emergency fund planner', metric: 'Months covered',
    short: 'Know how many months of essentials your savings cover.',
    description: 'Mark expenses as essential or not. FinSight divides your liquid savings by essential spending and compares it with the target you set.',
    points: ['Custom target from 1 to 24 months', 'Counts only liquid assets', 'Plain-language priority when reserves run short'] },
  { slug: 'goal-planning', title: 'Goal planning', metric: 'Goal funding',
    short: 'Retirement, house, education or travel, each with a date and a number.',
    description: 'Create goals with a target, date and monthly contribution. FinSight shows funding progress and the monthly amount needed under the return assumption you choose.',
    points: ['Return assumption is always visible', 'On track or behind, with the required monthly amount', 'Goals ranked by your priority'] },
  { slug: 'scenario-simulator', title: 'What-if scenarios', metric: 'Scenario delta',
    short: 'Try a raise, a new loan or lower spending without touching your data.',
    description: 'Change income, spending, extra savings or a new EMI and compare against your baseline side by side. Scenarios never modify your real records.',
    points: ['Side-by-side baseline vs scenario', 'Save scenarios for later', 'Clearly labelled as illustrative'] },
  { slug: 'financial-health-report', title: 'Financial health report', metric: 'Report',
    short: 'A readable report tied to a dated snapshot of your data.',
    description: 'Each report is built from an immutable snapshot, so it stays the same even if you edit your records later. An AI-written summary explains the numbers; the numbers themselves come from tested code.',
    points: ['Works without AI using a rules-based summary', 'Assumptions and disclosures included', 'Reproducible from its snapshot'] },
];
export const getFeature = (slug: string) => FEATURES.find((f) => f.slug === slug);
