// Config that drives the dynamic finance pages: one ResourceManager renders every resource from this map.
export type FieldType = 'text' | 'money' | 'number' | 'select' | 'date' | 'boolean';
export interface Field { name: string; label: string; type: FieldType; options?: [string, string][]; required?: boolean; placeholder?: string; nullable?: boolean }
export interface Resource { key: string; endpoint: string; title: string; singular: string; hint: string; fields: Field[]; columns: string[] }

const FREQ: [string, string][] = [['monthly', 'Monthly'], ['weekly', 'Weekly'], ['fortnightly', 'Every 2 weeks'], ['quarterly', 'Quarterly'], ['half_yearly', 'Every 6 months'], ['yearly', 'Yearly'], ['one_off', 'One-time']];
const opts = (...a: string[]): [string, string][] => a.map((x) => [x, x.replace(/_/g, ' ').replace(/^./, (c) => c.toUpperCase())]);

export const RESOURCES: Record<string, Resource> = {
  income: { key: 'income', endpoint: 'income', title: 'Income', singular: 'income source', hint: 'Regular income drives your ratios. One-time items are excluded.', columns: ['name', 'type', 'amountMinor', 'frequency'],
    fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'select', options: opts('salary', 'bonus', 'business', 'freelance', 'rental', 'interest', 'other') }, { name: 'amountMinor', label: 'Amount (₹)', type: 'money', required: true }, { name: 'frequency', label: 'How often', type: 'select', options: FREQ }] },
  expenses: { key: 'expenses', endpoint: 'expenses', title: 'Expenses', singular: 'expense', hint: 'Mark essentials so emergency-fund cover is accurate.', columns: ['name', 'category', 'amountMinor', 'frequency', 'essential'],
    fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'category', label: 'Category', type: 'text', placeholder: 'Housing, Food, Transport…', required: true }, { name: 'amountMinor', label: 'Amount (₹)', type: 'money', required: true }, { name: 'frequency', label: 'How often', type: 'select', options: FREQ }, { name: 'essential', label: 'Essential expense', type: 'boolean' }] },
  liabilities: { key: 'liabilities', endpoint: 'liabilities', title: 'Liabilities', singular: 'liability', hint: 'Add the EMI so debt payments are included. Leave it blank if unknown.', columns: ['name', 'type', 'outstandingMinor', 'emiMinor', 'interestRatePct'],
    fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'select', options: opts('home_loan', 'vehicle_loan', 'education_loan', 'personal_loan', 'credit_card', 'other') }, { name: 'outstandingMinor', label: 'Outstanding (₹)', type: 'money', required: true }, { name: 'emiMinor', label: 'EMI (₹)', type: 'money', nullable: true }, { name: 'frequency', label: 'EMI frequency', type: 'select', options: FREQ }, { name: 'interestRatePct', label: 'Interest rate (%)', type: 'number', nullable: true }] },
  assets: { key: 'assets', endpoint: 'assets', title: 'Assets', singular: 'asset', hint: 'Cash, deposits, gold, property. Put market investments under Investments.', columns: ['name', 'type', 'currentValueMinor', 'liquidityClass'],
    fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'select', options: opts('cash', 'bank', 'fixed_deposit', 'gold', 'property', 'vehicle', 'other') }, { name: 'currentValueMinor', label: 'Current value (₹)', type: 'money', required: true }, { name: 'liquidityClass', label: 'Liquidity', type: 'select', options: opts('liquid', 'semi_liquid', 'illiquid') }] },
  investments: { key: 'investments', endpoint: 'investments', title: 'Investments', singular: 'investment', hint: 'Track holdings by category. FinSight does not buy or sell.', columns: ['name', 'type', 'currentValueMinor', 'contributionMinor'],
    fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Category', type: 'select', options: opts('mutual_fund', 'stock', 'bond', 'nps', 'ppf', 'epf', 'crypto', 'other') }, { name: 'costBasisMinor', label: 'Amount invested (₹)', type: 'money', nullable: true }, { name: 'currentValueMinor', label: 'Current value (₹)', type: 'money', required: true }, { name: 'contributionMinor', label: 'Regular contribution (₹)', type: 'money' }, { name: 'contributionFrequency', label: 'Contribution frequency', type: 'select', options: FREQ }] },
  goals: { key: 'goals', endpoint: 'goals', title: 'Goals', singular: 'goal', hint: 'Each goal needs a target amount and date.', columns: ['name', 'category', 'targetAmountMinor', 'currentAmountMinor', 'targetDate'],
    fields: [{ name: 'name', label: 'Goal name', type: 'text', required: true }, { name: 'category', label: 'Category', type: 'select', options: opts('emergency', 'retirement', 'house', 'education', 'travel', 'wedding', 'custom') }, { name: 'targetAmountMinor', label: 'Target (₹)', type: 'money', required: true }, { name: 'currentAmountMinor', label: 'Saved so far (₹)', type: 'money' }, { name: 'monthlyContributionMinor', label: 'Monthly contribution (₹)', type: 'money' }, { name: 'targetDate', label: 'Target date', type: 'date', required: true }, { name: 'expectedReturnPct', label: 'Assumed annual return (%)', type: 'number' }, { name: 'priority', label: 'Priority (1 to 10)', type: 'number' }] },
};
export const FINANCIAL_TYPES = ['income', 'expenses', 'liabilities', 'assets', 'investments'] as const;
